// manifest.js — GENERATED by tools/build-manifest.mjs. Do not hand-edit.
window.SITE = {
  "title": "A Church Prepared for Revival",
  "subtitle": "A Pilot Proposed",
  "envLabel": "DEV",
  "license": {
    "label": "CC BY-SA 4.0",
    "url": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "repo": "https://github.com/jgtittle-ministries/a-church-prepared-for-revival-a-pilot-proposed-dev"
};

window.SERIES = [
  {
    "id": "index",
    "kind": "page",
    "name": "Home",
    "path": "docs/index.md"
  },
  {
    "id": "start-here",
    "kind": "page",
    "name": "Start here",
    "path": "docs/start-here.md"
  },
  {
    "id": "deciding-together",
    "kind": "page",
    "name": "Deciding Together — A Path for the Lead Pastor and Board",
    "path": "docs/deciding-together.md"
  },
  {
    "id": "movement-i-do-you-want-a-revival",
    "kind": "series",
    "name": "Movement I — Do You Want a Revival?",
    "nav": "Movement I",
    "folder": "docs/movement-i-do-you-want-a-revival",
    "edition": null,
    "index": "docs/movement-i-do-you-want-a-revival/index.md",
    "chapters": [
      {
        "path": "docs/movement-i-do-you-want-a-revival/index.md",
        "title": "Movement I — Do You Want a Revival?"
      },
      {
        "path": "docs/movement-i-do-you-want-a-revival/01-the-question.md",
        "title": "The Question"
      },
      {
        "path": "docs/movement-i-do-you-want-a-revival/02-the-seven-letters.md",
        "title": "The Seven Letters: What Christ Says to a Church"
      },
      {
        "path": "docs/movement-i-do-you-want-a-revival/03-what-the-record-shows.md",
        "title": "What the Record Shows"
      }
    ]
  },
  {
    "id": "movement-ii-what-is-your-soil",
    "kind": "series",
    "name": "Movement II — What Is Your Soil?",
    "nav": "Movement II",
    "folder": "docs/movement-ii-what-is-your-soil",
    "edition": null,
    "index": "docs/movement-ii-what-is-your-soil/index.md",
    "chapters": [
      {
        "path": "docs/movement-ii-what-is-your-soil/index.md",
        "title": "Movement II — What Is Your Soil?"
      },
      {
        "path": "docs/movement-ii-what-is-your-soil/01-the-four-soils.md",
        "title": "The Four Soils"
      },
      {
        "path": "docs/movement-ii-what-is-your-soil/02-hungry-hearts.md",
        "title": "Hungry Hearts"
      },
      {
        "path": "docs/movement-ii-what-is-your-soil/03-the-guardrails.md",
        "title": "The Guardrails"
      }
    ]
  },
  {
    "id": "movement-iii-preparing-the-soil",
    "kind": "series",
    "name": "Movement III — Preparing the Soil",
    "nav": "Movement III",
    "folder": "docs/movement-iii-preparing-the-soil",
    "edition": null,
    "index": "docs/movement-iii-preparing-the-soil/index.md",
    "chapters": [
      {
        "path": "docs/movement-iii-preparing-the-soil/index.md",
        "title": "Movement III — Preparing the Soil"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/01-it-starts-at-the-top.md",
        "title": "It Starts at the Top"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/02-the-vessel-before-the-rain.md",
        "title": "The Vessel Before the Rain"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/03-the-practices-that-till.md",
        "title": "The Practices That Till"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/04-when-the-ground-goes-dry.md",
        "title": "When the Ground Goes Dry"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/05-who-watches-the-shepherds.md",
        "title": "Who Watches the Shepherds?"
      },
      {
        "path": "docs/movement-iii-preparing-the-soil/06-the-pilot-season-by-season.md",
        "title": "The Pilot, Season by Season"
      }
    ]
  },
  {
    "id": "movement-iv-keeping-what-comes",
    "kind": "series",
    "name": "Movement IV — Keeping What Comes",
    "nav": "Movement IV",
    "folder": "docs/movement-iv-keeping-what-comes",
    "edition": null,
    "index": "docs/movement-iv-keeping-what-comes/index.md",
    "chapters": [
      {
        "path": "docs/movement-iv-keeping-what-comes/index.md",
        "title": "Movement IV — Keeping What Comes"
      },
      {
        "path": "docs/movement-iv-keeping-what-comes/01-the-drift-downward.md",
        "title": "The Drift Downward"
      },
      {
        "path": "docs/movement-iv-keeping-what-comes/02-how-revivals-were-lost.md",
        "title": "How Revivals Were Lost"
      },
      {
        "path": "docs/movement-iv-keeping-what-comes/04-handing-the-fire.md",
        "title": "Handing the Fire"
      }
    ]
  },
  {
    "id": "reference",
    "kind": "series",
    "name": "Reference",
    "nav": "Reference",
    "folder": "docs/reference",
    "edition": null,
    "index": "docs/reference/index.md",
    "chapters": [
      {
        "path": "docs/reference/index.md",
        "title": "Reference"
      },
      {
        "path": "docs/reference/01-how-these-foundations-were-tested.md",
        "title": "How These Foundations Were Tested"
      }
    ]
  }
];

window.PATH_TO_INFO = {
  "docs/index.md": {
    "seriesId": "index",
    "seriesName": "Home",
    "title": "Home",
    "indexPath": "docs/index.md",
    "next": "docs/start-here.md"
  },
  "docs/start-here.md": {
    "seriesId": "start-here",
    "seriesName": "Start here",
    "title": "Start here",
    "indexPath": "docs/start-here.md",
    "prev": "docs/index.md",
    "next": "docs/deciding-together.md"
  },
  "docs/deciding-together.md": {
    "seriesId": "deciding-together",
    "seriesName": "Deciding Together — A Path for the Lead Pastor and Board",
    "title": "Deciding Together — A Path for the Lead Pastor and Board",
    "indexPath": "docs/deciding-together.md",
    "prev": "docs/start-here.md",
    "next": "docs/movement-i-do-you-want-a-revival/index.md"
  },
  "docs/movement-i-do-you-want-a-revival/index.md": {
    "seriesId": "movement-i-do-you-want-a-revival",
    "seriesName": "Movement I — Do You Want a Revival?",
    "title": "Movement I — Do You Want a Revival?",
    "indexPath": "docs/movement-i-do-you-want-a-revival/index.md",
    "prev": "docs/deciding-together.md",
    "next": "docs/movement-i-do-you-want-a-revival/01-the-question.md"
  },
  "docs/movement-i-do-you-want-a-revival/01-the-question.md": {
    "seriesId": "movement-i-do-you-want-a-revival",
    "seriesName": "Movement I — Do You Want a Revival?",
    "title": "The Question",
    "indexPath": "docs/movement-i-do-you-want-a-revival/index.md",
    "prev": "docs/movement-i-do-you-want-a-revival/index.md",
    "next": "docs/movement-i-do-you-want-a-revival/02-the-seven-letters.md"
  },
  "docs/movement-i-do-you-want-a-revival/02-the-seven-letters.md": {
    "seriesId": "movement-i-do-you-want-a-revival",
    "seriesName": "Movement I — Do You Want a Revival?",
    "title": "The Seven Letters: What Christ Says to a Church",
    "indexPath": "docs/movement-i-do-you-want-a-revival/index.md",
    "prev": "docs/movement-i-do-you-want-a-revival/01-the-question.md",
    "next": "docs/movement-i-do-you-want-a-revival/03-what-the-record-shows.md"
  },
  "docs/movement-i-do-you-want-a-revival/03-what-the-record-shows.md": {
    "seriesId": "movement-i-do-you-want-a-revival",
    "seriesName": "Movement I — Do You Want a Revival?",
    "title": "What the Record Shows",
    "indexPath": "docs/movement-i-do-you-want-a-revival/index.md",
    "prev": "docs/movement-i-do-you-want-a-revival/02-the-seven-letters.md",
    "next": "docs/movement-ii-what-is-your-soil/index.md"
  },
  "docs/movement-ii-what-is-your-soil/index.md": {
    "seriesId": "movement-ii-what-is-your-soil",
    "seriesName": "Movement II — What Is Your Soil?",
    "title": "Movement II — What Is Your Soil?",
    "indexPath": "docs/movement-ii-what-is-your-soil/index.md",
    "prev": "docs/movement-i-do-you-want-a-revival/03-what-the-record-shows.md",
    "next": "docs/movement-ii-what-is-your-soil/01-the-four-soils.md"
  },
  "docs/movement-ii-what-is-your-soil/01-the-four-soils.md": {
    "seriesId": "movement-ii-what-is-your-soil",
    "seriesName": "Movement II — What Is Your Soil?",
    "title": "The Four Soils",
    "indexPath": "docs/movement-ii-what-is-your-soil/index.md",
    "prev": "docs/movement-ii-what-is-your-soil/index.md",
    "next": "docs/movement-ii-what-is-your-soil/02-hungry-hearts.md"
  },
  "docs/movement-ii-what-is-your-soil/02-hungry-hearts.md": {
    "seriesId": "movement-ii-what-is-your-soil",
    "seriesName": "Movement II — What Is Your Soil?",
    "title": "Hungry Hearts",
    "indexPath": "docs/movement-ii-what-is-your-soil/index.md",
    "prev": "docs/movement-ii-what-is-your-soil/01-the-four-soils.md",
    "next": "docs/movement-ii-what-is-your-soil/03-the-guardrails.md"
  },
  "docs/movement-ii-what-is-your-soil/03-the-guardrails.md": {
    "seriesId": "movement-ii-what-is-your-soil",
    "seriesName": "Movement II — What Is Your Soil?",
    "title": "The Guardrails",
    "indexPath": "docs/movement-ii-what-is-your-soil/index.md",
    "prev": "docs/movement-ii-what-is-your-soil/02-hungry-hearts.md",
    "next": "docs/movement-iii-preparing-the-soil/index.md"
  },
  "docs/movement-iii-preparing-the-soil/index.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "Movement III — Preparing the Soil",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-ii-what-is-your-soil/03-the-guardrails.md",
    "next": "docs/movement-iii-preparing-the-soil/01-it-starts-at-the-top.md"
  },
  "docs/movement-iii-preparing-the-soil/01-it-starts-at-the-top.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "It Starts at the Top",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/index.md",
    "next": "docs/movement-iii-preparing-the-soil/02-the-vessel-before-the-rain.md"
  },
  "docs/movement-iii-preparing-the-soil/02-the-vessel-before-the-rain.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "The Vessel Before the Rain",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/01-it-starts-at-the-top.md",
    "next": "docs/movement-iii-preparing-the-soil/03-the-practices-that-till.md"
  },
  "docs/movement-iii-preparing-the-soil/03-the-practices-that-till.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "The Practices That Till",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/02-the-vessel-before-the-rain.md",
    "next": "docs/movement-iii-preparing-the-soil/04-when-the-ground-goes-dry.md"
  },
  "docs/movement-iii-preparing-the-soil/04-when-the-ground-goes-dry.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "When the Ground Goes Dry",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/03-the-practices-that-till.md",
    "next": "docs/movement-iii-preparing-the-soil/05-who-watches-the-shepherds.md"
  },
  "docs/movement-iii-preparing-the-soil/05-who-watches-the-shepherds.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "Who Watches the Shepherds?",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/04-when-the-ground-goes-dry.md",
    "next": "docs/movement-iii-preparing-the-soil/06-the-pilot-season-by-season.md"
  },
  "docs/movement-iii-preparing-the-soil/06-the-pilot-season-by-season.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "The Pilot, Season by Season",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/05-who-watches-the-shepherds.md",
    "next": "docs/movement-iv-keeping-what-comes/index.md"
  },
  "docs/movement-iv-keeping-what-comes/index.md": {
    "seriesId": "movement-iv-keeping-what-comes",
    "seriesName": "Movement IV — Keeping What Comes",
    "title": "Movement IV — Keeping What Comes",
    "indexPath": "docs/movement-iv-keeping-what-comes/index.md",
    "prev": "docs/movement-iii-preparing-the-soil/06-the-pilot-season-by-season.md",
    "next": "docs/movement-iv-keeping-what-comes/01-the-drift-downward.md"
  },
  "docs/movement-iv-keeping-what-comes/01-the-drift-downward.md": {
    "seriesId": "movement-iv-keeping-what-comes",
    "seriesName": "Movement IV — Keeping What Comes",
    "title": "The Drift Downward",
    "indexPath": "docs/movement-iv-keeping-what-comes/index.md",
    "prev": "docs/movement-iv-keeping-what-comes/index.md",
    "next": "docs/movement-iv-keeping-what-comes/02-how-revivals-were-lost.md"
  },
  "docs/movement-iv-keeping-what-comes/02-how-revivals-were-lost.md": {
    "seriesId": "movement-iv-keeping-what-comes",
    "seriesName": "Movement IV — Keeping What Comes",
    "title": "How Revivals Were Lost",
    "indexPath": "docs/movement-iv-keeping-what-comes/index.md",
    "prev": "docs/movement-iv-keeping-what-comes/01-the-drift-downward.md",
    "next": "docs/movement-iv-keeping-what-comes/04-handing-the-fire.md"
  },
  "docs/movement-iv-keeping-what-comes/04-handing-the-fire.md": {
    "seriesId": "movement-iv-keeping-what-comes",
    "seriesName": "Movement IV — Keeping What Comes",
    "title": "Handing the Fire",
    "indexPath": "docs/movement-iv-keeping-what-comes/index.md",
    "prev": "docs/movement-iv-keeping-what-comes/02-how-revivals-were-lost.md",
    "next": "docs/reference/index.md"
  },
  "docs/reference/index.md": {
    "seriesId": "reference",
    "seriesName": "Reference",
    "title": "Reference",
    "indexPath": "docs/reference/index.md",
    "prev": "docs/movement-iv-keeping-what-comes/04-handing-the-fire.md",
    "next": "docs/reference/01-how-these-foundations-were-tested.md"
  },
  "docs/reference/01-how-these-foundations-were-tested.md": {
    "seriesId": "reference",
    "seriesName": "Reference",
    "title": "How These Foundations Were Tested",
    "indexPath": "docs/reference/index.md",
    "prev": "docs/reference/index.md"
  }
};
