// manifest.js — GENERATED by tools/build-manifest.mjs. Do not hand-edit.
window.SITE = {
  "title": "A Church in Revival",
  "subtitle": "A Pilot Proposed",
  "envLabel": "DEV",
  "license": {
    "label": "CC BY-SA 4.0",
    "url": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "repo": "https://github.com/jgtittle-ministries/a-church-in-revival-a-pilot-proposed-dev"
};

window.SERIES = [
  {
    "id": "index",
    "kind": "page",
    "name": "Home",
    "path": "docs/index.md"
  },
  {
    "id": "start-here",
    "kind": "page",
    "name": "Start here",
    "path": "docs/start-here.md"
  },
  {
    "id": "movement-i-do-you-want-a-revival",
    "kind": "series",
    "name": "Movement I — Do You Want a Revival?",
    "folder": "docs/movement-i-do-you-want-a-revival",
    "edition": null,
    "index": "docs/movement-i-do-you-want-a-revival/index.md",
    "chapters": [
      {
        "path": "docs/movement-i-do-you-want-a-revival/index.md",
        "title": "Movement I — Do You Want a Revival?"
      }
    ]
  },
  {
    "id": "movement-ii-what-is-your-soil",
    "kind": "series",
    "name": "Movement II — What Is Your Soil?",
    "folder": "docs/movement-ii-what-is-your-soil",
    "edition": null,
    "index": "docs/movement-ii-what-is-your-soil/index.md",
    "chapters": [
      {
        "path": "docs/movement-ii-what-is-your-soil/index.md",
        "title": "Movement II — What Is Your Soil?"
      }
    ]
  },
  {
    "id": "movement-iii-preparing-the-soil",
    "kind": "series",
    "name": "Movement III — Preparing the Soil",
    "folder": "docs/movement-iii-preparing-the-soil",
    "edition": null,
    "index": "docs/movement-iii-preparing-the-soil/index.md",
    "chapters": [
      {
        "path": "docs/movement-iii-preparing-the-soil/index.md",
        "title": "Movement III — Preparing the Soil"
      }
    ]
  },
  {
    "id": "movement-iv-keeping-what-comes",
    "kind": "series",
    "name": "Movement IV — Keeping What Comes",
    "folder": "docs/movement-iv-keeping-what-comes",
    "edition": null,
    "index": "docs/movement-iv-keeping-what-comes/index.md",
    "chapters": [
      {
        "path": "docs/movement-iv-keeping-what-comes/index.md",
        "title": "Movement IV — Keeping What Comes"
      }
    ]
  },
  {
    "id": "reference",
    "kind": "series",
    "name": "Reference",
    "folder": "docs/reference",
    "edition": null,
    "index": "docs/reference/index.md",
    "chapters": [
      {
        "path": "docs/reference/index.md",
        "title": "Reference"
      }
    ]
  }
];

window.PATH_TO_INFO = {
  "docs/index.md": {
    "seriesId": "index",
    "seriesName": "Home",
    "title": "Home",
    "indexPath": "docs/index.md"
  },
  "docs/start-here.md": {
    "seriesId": "start-here",
    "seriesName": "Start here",
    "title": "Start here",
    "indexPath": "docs/start-here.md"
  },
  "docs/movement-i-do-you-want-a-revival/index.md": {
    "seriesId": "movement-i-do-you-want-a-revival",
    "seriesName": "Movement I — Do You Want a Revival?",
    "title": "Movement I — Do You Want a Revival?",
    "indexPath": "docs/movement-i-do-you-want-a-revival/index.md"
  },
  "docs/movement-ii-what-is-your-soil/index.md": {
    "seriesId": "movement-ii-what-is-your-soil",
    "seriesName": "Movement II — What Is Your Soil?",
    "title": "Movement II — What Is Your Soil?",
    "indexPath": "docs/movement-ii-what-is-your-soil/index.md"
  },
  "docs/movement-iii-preparing-the-soil/index.md": {
    "seriesId": "movement-iii-preparing-the-soil",
    "seriesName": "Movement III — Preparing the Soil",
    "title": "Movement III — Preparing the Soil",
    "indexPath": "docs/movement-iii-preparing-the-soil/index.md"
  },
  "docs/movement-iv-keeping-what-comes/index.md": {
    "seriesId": "movement-iv-keeping-what-comes",
    "seriesName": "Movement IV — Keeping What Comes",
    "title": "Movement IV — Keeping What Comes",
    "indexPath": "docs/movement-iv-keeping-what-comes/index.md"
  },
  "docs/reference/index.md": {
    "seriesId": "reference",
    "seriesName": "Reference",
    "title": "Reference",
    "indexPath": "docs/reference/index.md"
  }
};
